
---
  - hosts: all
    remote_user: ubuntu
    become: true
    become_user: root
    vars:
      packages: {
           bionic: /etc/netplan/50-cloud-init.yaml,
           focal: /etc/netplan/00-installer-config.yaml
          }


    tasks:

      - name: "change ip"
        replace:
          path: "{{ packages[ansible_distribution_release] }}"
          regexp: "{{ old_ip }}"
          replace: "{{ new_ip }}"


      - become: true
        become_user: ubuntu
        block:

          - name: "copy gitlab ssh key"
            copy:
              src: ssh_keys/id_rsa
              dest: ~/.ssh/id_rsa
              mode: '600'

          - block:
              - name: "copy ssh priv key to Ansible control node"
                copy:
                  src: ssh_keys/control_node
                  dest: ~/.ssh/ctrl_id
                  mode: '600'

              - name: git clone schema repo on localhost
                ansible.builtin.git:
                  dest: ~/apiculus-play
                  single_branch: yes
                  accept_hostkey: yes
                  repo: git@gitlab.indiqus.net:devops/apiculus-play.git
                  version: dev
            when: ctrl_node is defined
          
          - name: "copy pub ssh keys to cb/db clusters"
            blockinfile:
              path: ~/.ssh/authorized_keys
              create: yes
              state: present
              block: "{{ lookup('file', 'ssh_keys/control_node.pub') }}"
            when: ctrl_node is not defined



      - name: "reboot to populate new ip"
        command: reboot
        ignore_errors: yes
